[workspace]
resolver = "2"
members = [
    "kvm-core",
    "kvm-protocol",
    "kvm-platform",
    "kvm-daemon",
    "kvm-ui",
]

[workspace.package]
version = "0.9.4"
edition = "2021"
license = "GPL-3.0-or-later"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rcgen = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
