[package]
name = "kvm-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kvm-daemon"
path = "src/main.rs"

[dependencies]
kvm-core = { path = "../kvm-core" }
kvm-protocol = { path = "../kvm-protocol" }
kvm-platform = { path = "../kvm-platform" }
quinn = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = "1"
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_RemoteDesktop",
    "Win32_System_Services",
    "Win32_System_StationsAndDesktops",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
getrandom = "0.3"
